### ISSUE TITLE
Question about the data processing

### ISSUE THREAD

**Issue by yl-wang996** [Jiyao06/GenPose#10]
As in file `/datasets/datasets_genpose.py`, lines 673-674, you use the same one `PC_da`  as the points cloud input, also for the color input. Is it a typo there?  

    processed_sample['pts'] = PC_da                # [bs, 1024, 3]
    processed_sample['pts_color'] = PC_da          # [bs, 1024, 3]

As my understanding, the `PC_da`  should be the points cloud, not the color. So I am confused with it.

Any of your answers will be  grateful.

**Comment by Jiyao06** [comment]
Sorry for any confusion. Regarding the use of `PC_da` as both point cloud data and color information, this is because our network only uses the point cloud data as input, while the color data is included for visualization purposes in rendering.

Thanks for the attention you've given to our work.

**Comment by yl-wang996** [comment]
Thanks a lot.
