### ISSUE TITLE
quaternion vs. 6d representation

### ISSUE THREAD

**Issue by eric-zqwang** [Jiyao06/GenPose#11]
Hi, 

I am curious about the use of quaternion and 6d representations for rotational parameters. I've noticed that you utilize a 6D representation in GenPose. My question is, when using quaternions for these rotational parameters, does it lead to a decrease in performance? Or are there any significant issues when deniose the quaternion parameter?

**Comment by Jiyao06** [comment]
We chose the 6D representation in GenPose over quaternions to address the discontinuity of quaternions and Euler angles in Euclidean space, following the approaches in references [1, 2]. This ensures better performance and stability in handling rotational parameters.

[1] Wei Chen, Xi Jia, Hyung Jin Chang, Jinming Duan, Linlin Shen, and Ales Leonardis. Fs-net:
Fast shape-based network for category-level 6d object pose estimation with decoupled rotation
mechanism. In Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern
Recognition, pages 1581–1590, 2021.
[2] Yi Zhou, Connelly Barnes, Jingwan Lu, Jimei Yang, and Hao Li. On the continuity of rotation
representations in neural networks. In Proceedings of the IEEE/CVF Conference on Computer
Vision and Pattern Recognition, pages 5745–5753, 2019.

**Comment by eric-zqwang** [comment]
Thank you for your reply. I was wondering if you have done any experiments to see how much the 6d representation improves performance over the quaternion representation in your task?

**Comment by Jiyao06** [comment]
Thank you for your question. In our preliminary tests on data about 1/10th the size of our full dataset, the 6D representation showed an advantage (however, it was not an extremely significant leap). We didn't conduct these comparisons on the entire dataset, but we're planning to conduct more extensive testing in our future work. Keep an eye out for further updates!

**Comment by eric-zqwang** [comment]
Thank you so much.
