### ISSUE TITLE
关于实时位姿估计

### ISSUE THREAD

**Issue by fuzhao123232** [Jiyao06/GenPose#12]
首先非常感觉作者的SOTA工作。然后有一个问题就是我看原文的时候，有说到位姿追踪的FPS是17，那么我是不是可以理解为一次位姿估计的时间是1000/17 ms？还是说第一帧的时间和后续追踪的时间是不一样的？

**Comment by Jiyao06** [comment]
Yes, the 17 FPS mentioned refers to the speed of pose tracking. For the first frame, we utilized a perturbed ground truth pose as the initial object pose, following CAPTRA[1]. 

[1] Yijia Weng, He Wang, Qiang Zhou, Yuzhe Qin, Yueqi Duan, Qingnan Fan, Baoquan Chen, Hao
Su, and Leonidas J Guibas. Captra: Category-level pose tracking for rigid and articulated objects
from point clouds. In Proceedings of the IEEE/CVF International Conference on Computer
Vision, pages 13209–13218, 2021.
