### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by gen4u** [Jiyao06/GenPose#13]
Hi, thanks for your great work!

As a newcomer to this domain, I am facing challenges in visualizing these results effectively. 

1. **RGB Image Visualization**: Could you provide instructions or code snippets for overlaying estimated object poses on RGB images?
2. **3D Point Cloud Visualization**: Do you have recommendations or code examples for visualizing estimated poses in a 3D point cloud?

**Comment by Jiyao06** [comment]
**1. RGB Image Visualization:** For overlaying estimated object poses on RGB images, you can use the `draw_detections_with_error` function available in `utils.sgpa_utils`. 

**2. 3D Point Cloud Visualization:** For visualizing estimated poses in a 3D point cloud, I recommend using the `open3d` library, which is a powerful and user-friendly open-source library for 3D data processing.
