### ISSUE TITLE
about real dataset's pts abnormal

### ISSUE THREAD

**Issue by fuzhao123232** [Jiyao06/GenPose#15]
![image](https://github.com/Jiyao06/GenPose/assets/115547529/cdf17cf8-58a6-4341-b3e0-cd64139ceeb8)
train的时候，我可视化了输入的点云，最后发现，Real数据集上的点云存在异常，这是因为代码生成的问题？还是mask不太好导致的？这会影响结果导致泛化到实例场景的时候效果较差吗？

**Comment by fuzhao123232** [comment]
![image](https://github.com/Jiyao06/GenPose/assets/115547529/e7ecfc28-99e7-4223-83ae-57b65764d99f)
作者的源代码中，NOCSdataset那个类，get_item那个方法中把深度图结合mask扣除目标生成点云的代码如上，我看源代码的时候，里面似乎涉及把bbox的中心点和长度做了随机的shift和scale，不知道会不会是这个原因导致的上述的问题？

**Comment by Jiyao06** [comment]
The `crop_resize_by_warp_affine` function is for data augmentation. The noise in the real point clouds is due to inaccuracies in mask annotations.

**Comment by fuzhao123232** [comment]
Thank you
