### ISSUE TITLE
how to set K=50 when eval

### ISSUE THREAD

**Issue by fuzhao123232** [Jiyao06/GenPose#16]
![image](https://github.com/Jiyao06/GenPose/assets/115547529/ef35a45f-a102-42fb-a375-6cb9080c40af)
dear author, i have run bash eval_single.bash get the results as follow:
![image](https://github.com/Jiyao06/GenPose/assets/115547529/587c04fd-02b6-4e47-bba0-d9520f7f1359)
It seems to be K=1 ,bucause in the table when K=50, it can get a better results. But in the code, I can't find the parameter K, I don't know how to set K = 50.

**Comment by fuzhao123232** [comment]
![image](https://github.com/Jiyao06/GenPose/assets/115547529/ab38449b-24e1-4238-8fba-8b9aff930083)

**Comment by fuzhao123232** [comment]
![image](https://github.com/Jiyao06/GenPose/assets/115547529/02fb2696-d53a-4847-810c-1438341458cb)
代码里面，预测的pose的dim就是50，这个就是K？但是这个结果最后评估的结果是
![image](https://github.com/Jiyao06/GenPose/assets/115547529/d3e92534-0183-4c4d-a164-f37f8032f342)
那么这个结果是怎么来的
![image](https://github.com/Jiyao06/GenPose/assets/115547529/d0e5d423-5f7b-4738-a8ae-20704a17c8b8)
我是因为看到了这个结果，感到很惊讶，和之前的SOTA提升了很多，所以想复现一下结果的

**Comment by Jiyao06** [comment]
The "Ours" column in the table represents the results obtained using our proposed energy-based pose aggregation algorithm, not the results for K=1. For detailed explanations of each item in the table, please refer to Section 4.2 of our paper.

<img width="890" alt="image" src="https://github.com/Jiyao06/GenPose/assets/88179466/79150120-967f-487a-8fd3-25abae11ad33">

**Comment by fuzhao123232** [comment]
抱歉，我现在看懂了
![image](https://github.com/Jiyao06/GenPose/assets/115547529/1363d71b-f49f-4f49-a043-a6481e6a8091)
这个的结果是使用energy network 然后做rank，outliner filter 和mean pool的pose和gt的一个eval结果。
![image](https://github.com/Jiyao06/GenPose/assets/115547529/720dd46b-4aa7-48a0-aba1-10fb62a4b5dd)
这lian两个是从20和50个score network预测的poses里面选择距离gt最小的计算的一个eval的结果。
