### ISSUE TITLE
Segmentation Fault Occurs When Running 'bash scripts/eval_single.sh'

### ISSUE THREAD

**Issue by qiqi7749** [Jiyao06/GenPose#17]
Hello, and thank you for your SOTA work.

I encountered a segmentation fault when running `bash scripts/eval_single.sh`. The error occurs during the forward pass, specifically in `GenPose/networks/pts_encoder/pointnet2_utils/pointnet2/pointnet2_modules.py` at line 40, within the `forward` function of the `_PointnetSAModuleBase` class. The segmentation fault occurs at the line `new_features = self.mlps[0](new_features)`.
![20240131-094545](https://github.com/Jiyao06/GenPose/assets/140774285/06fa8818-21f6-4665-a6b1-120a4fd0ff9c)

I suspect that the issue may be due to a mismatch between the loaded checkpoint file `ckpt_genpose.pth` and the model. In an attempt to resolve this, I trained the model myself using the `bash scripts/train_score.sh` and `bash scripts/train_energy.sh` commands. Here are the training parameters I used:

`train_score.sh`:
![image](https://github.com/Jiyao06/GenPose/assets/140774285/fdcc8d33-8d7d-4f3a-aafe-d2939d43f795)

`train_energy.sh`:
![image](https://github.com/Jiyao06/GenPose/assets/140774285/97eb66a4-6005-455a-924e-84a12078db63)

However, even with the model trained by myself, I still encounter the segmentation fault at the same location when calling `bash scripts/eval_single.sh`. I used `print` to print `self.mlps.size()`, `type(self.mlps[i])`, `new_features.type()`, and `new_feature.size()`, and the results were consistent with those during training. Strangely, training does not result in a segmentation fault.

Here is my `eval_single.sh`:
![image](https://github.com/Jiyao06/GenPose/assets/140774285/dfbe86d6-9b5a-4743-a583-3f15137fc183)

I would appreciate any insights you may have into the possible reasons for the segmentation fault. 
Thank you once again!

**Comment by Jiyao06** [comment]
This issue might be related to the versions of certain libraries you are using. Could you please confirm whether the library versions you're using match the versions recommended in our repo?

**Comment by qiqi7749** [comment]
> This issue might be related to the versions of certain libraries you are using. Could you please confirm whether the library versions you're using match the versions recommended in our repo?

Thank you. It might be related to the environment. I'll try rebuilding the environment to see if it resolves the issue.

**Comment by qiqi7749** [comment]
> This issue might be related to the versions of certain libraries you are using. Could you please confirm whether the library versions you're using match the versions recommended in our repo?

Thank you for the guidance. After using the recommended environment from the repository, I was able to run the code smoothly. Additionally, I debugged the previous code using `gdb python` and found that the segmentation fault occurs in `/usr/lib/x86_64-linux-gnu/libcuda.so.1`. It indeed seems to be related to the environment.
