### ISSUE TITLE
Error when loading results_test_scene_4_0000.pkl file in aligned_real_test folder

### ISSUE THREAD

**Issue by qiaoda-da** [Jiyao06/GenPose#18]
Thank you for sharing this amazing project.

I encountered a problem when I tried to run the tracking file on the aligned_real_test folder. When I loaded the results_test_scene_4_0000.pkl and results_test_scene_4_0001.pkl file, I got an error message saying "pickle data was truncated".  I wonder what caused this error and how to fix it.

The _pickle version I use is as follows, and when I load the file separately, I also get this prompt.
![pickle version](https://github.com/Jiyao06/GenPose/assets/62348978/313594d9-0066-4686-9859-c7df7821682d)
![image](https://github.com/Jiyao06/GenPose/assets/62348978/2dae2f3f-25ff-4c1d-9922-584f0e0dcbfd)

**Comment by fuzhao123232** [comment]
Maybe the file to be read is damaged. I didn't meet this question. You can try to redownload it.

**Comment by qiaoda-da** [comment]
> Maybe the file to be read is damaged. I didn't meet this question. You can try to redownload it.

I have tried to download it several times, and the file size is the same every time, so the file should not be damaged. I don’t know what caused this problem. Thank you for your reply.

**Comment by fuzhao123232** [comment]
![image](https://github.com/Jiyao06/GenPose/assets/115547529/72f3a772-d3de-483a-b148-23977240f974)
![image](https://github.com/Jiyao06/GenPose/assets/115547529/b37fa424-5565-4c6e-b747-8d4bdea9479c)
There are two positions for real_test, and I don't know which one you used, but I think you can try another one.

**Comment by fuzhao123232** [comment]
![image](https://github.com/Jiyao06/GenPose/assets/115547529/619be573-3118-484f-8b98-70f58753745e)
Is the same?

**Comment by qiaoda-da** [comment]
![image](https://github.com/Jiyao06/GenPose/assets/62348978/a2531513-4fd2-4857-acef-96cdf20d75f6)
I used the pkl file in the aligned_real_test folder provided by the author.
![image](https://github.com/Jiyao06/GenPose/assets/62348978/da214d18-96a2-4f44-8767-f2690c39ce46)
The pkl file in the **mrcnn_results/real_test** folder is fine.

**Comment by fuzhao123232** [comment]
I think you can just skip this two files, it just influence test and just two files is small. 2/2755 is really small.
说了半天发现你是中国人，两个gt文件跳过把，影响不大的。时间就是生命，别浪费时间在这点小细节上
![image](https://github.com/Jiyao06/GenPose/assets/115547529/1b8a3ba1-1764-4643-87e7-722f0e8632a0)

**Comment by fuzhao123232** [comment]
![image](https://github.com/Jiyao06/GenPose/assets/115547529/2872c7cb-ea85-42c2-b496-e3066b6a3b4c)
just like this. If the file is bad, just skip

**Comment by qiaoda-da** [comment]
Thank you for your reply. I will try to skip some corrupted files and check how the evaluation results are. 
谢谢哈，我跳过这些文件，看下结果如何。

**Comment by Jiyao06** [comment]
Apologies for the confusion caused. I have updated the data download link. Please try downloading the file again.

**Comment by qiaoda-da** [comment]
Thank you for your reply, thank you.
