### ISSUE TITLE
Code available

### ISSUE THREAD

**Issue by Michaelswitch** [Jiyao06/GenPose#2]
Hello, nice to see your work, when will the code be available?

**Comment by Jiyao06** [comment]
Thank you for your interest! The code will be available within the next two weeks. Please continue to follow our GitHub repository for updates.

**Comment by DHuiTnut** [comment]
Hello, have you done with the codes? Looking forward to it.

> Thank you for your interest! The code will be available within the next two weeks. Please continue to follow our GitHub repository for updates.
