### ISSUE TITLE
pooling mode

### ISSUE THREAD

**Issue by fuzhao123232** [Jiyao06/GenPose#21]
In author's paper, mean pooling's result as follow:
![image](https://github.com/Jiyao06/GenPose/assets/115547529/e179c9e3-650a-496f-85b6-627f74235f5b)
and I test it as follow:
![image](https://github.com/Jiyao06/GenPose/assets/115547529/7500f9cb-aca1-4b54-8b7d-925aa0e6d8ed)

But in the codes, using pooling mode='nearest', I got a better result as follw:
![image](https://github.com/Jiyao06/GenPose/assets/115547529/49789897-3c50-4b7f-ae37-897650fc89b7)
![image](https://github.com/Jiyao06/GenPose/assets/115547529/7b1dfbda-83f6-4f1a-9023-d4d96a92126a)

But the results of 3D iou is the same,  I don't know why?

**Comment by Jiyao06** [comment]
1. In the 'nearest' pooling mode, we evaluate the performance by considering the error of the nearest candidate to the ground truth pose, which explains the enhanced performance observed.

2. This work focuses on 6D pose estimation for objects, not 9D, therefore we do not evaluate 3D IoU metrics. Regarding the IoU metric, the reference to "3D IoU" in the screenshot should indeed be "2D IoU". This was a mistake in the code output on my part. I apologize for any confusion this has caused, and I will promptly update the repository to fix the bug.
