### ISSUE TITLE
question regarding the score-based diffusion model

### ISSUE THREAD

**Issue by yl-wang996** [Jiyao06/GenPose#22]
I am not an expert on the diffusion model, so I have a question about it:

- why did you choose to use the score-based diffusion model to estimate the pose? 
- and why not the stable diffusion?   
- What are the main pros and cons of the score-based diffusion model(accuracy, speed, or ...)?  

I will be grateful if you take several minutes to answer my question.
Best Regards

**Comment by Jiyao06** [comment]
Thank you for your interest. Regarding your question, we actually did not test the DDPM method. However, the DDPM method can be amalgamated into the framework of the score-based diffusion model as a discretization of separate SDE. I hope this answers your question.
