### ISSUE TITLE
About diffusion process

### ISSUE THREAD

**Issue by sseunghyuns** [Jiyao06/GenPose#24]
Thanks for your great work!

Why did you use **VE-SDE** instead of  **VP-SDE** (variance preserving) for the ScoreNet & EnergyNet? Is it because the performance was better experimentally?
If there are any related experimental results, I would like to know how much the difference was!

Thank you.

**Comment by Jiyao06** [comment]
Indeed, in the early stages of small-scale experimentation, VE-SDE exhibited better performance. Unfortunately, the comprehensive experiment on the full dataset was not conducted at this stage. Your suggestion is well-noted, and I plan to supplement more extensive experiments in the subsequent phases of our work. Thanks!
