### ISSUE TITLE
训练时间问题

### ISSUE THREAD

**Issue by upc-ghy** [Jiyao06/GenPose#27]
大佬您好，我正常按照您的readme执行，到了bash scripts/train_score.sh这一步时，训练了好多天都没还有结束，我没有改动你的代码，我用的是4090，依然很慢。

![image](https://github.com/Jiyao06/GenPose/assets/133858812/7fb455ed-5249-4e7b-ae2a-f23c8081e57e)

CPU利用率都很低，显卡占了20多G，我不知道怎么提速。。

**Comment by Jiyao06** [comment]
Hi，please refer to #19

**Comment by Jiyao06** [comment]
Please refer to #14.
