### ISSUE TITLE
About Energy-Error Correlation Analysis

### ISSUE THREAD

**Issue by sseunghyuns** [Jiyao06/GenPose#29]
Hello,

When generating the Energy-Error Correlation Analysis plot, did you use the sgpa_utils.compute_RT_errors function to calculate the error between the 4x4 RT matrix sampled by ScoreNet and the ground truth RT? 

Also, did you extract the results for the entire real_test dataset?

<img width="935" alt="image" src="https://github.com/Jiyao06/GenPose/assets/63924704/1e0641fb-6f4f-4a1d-b897-f06c902b625d">

Thank you!

**Comment by Jiyao06** [comment]
Yes, we used the `sgpa_utils.compute_RT_errors` function for the plot and analyzed the entire real_test dataset.
