### ISSUE TITLE
跟踪代码

### ISSUE THREAD

**Issue by huiyang0613** [Jiyao06/GenPose#3]
非常感谢您提供这么棒的工作~在您的论文中我看到您有做跟踪相关的工作，请问后续您会开源跟踪的代码吗？

**Comment by Jiyao06** [comment]
We intend to release the code for our tracking system, along with the preprocessed data. Please stay tuned for updates on this repository.

**Comment by huiyang0613** [comment]
> We intend to release the code for our tracking system, along with the preprocessed data. Please stay tuned for updates on this repository.
非常期待~
