### ISSUE TITLE
How to grasp?

### ISSUE THREAD

**Issue by fkendlessly** [Jiyao06/GenPose#31]
Dear author, Thanks for your work. After obtaining the pose, how is the grasping determined? For example, grasping a cup or grasping a bowl.

**Comment by Jiyao06** [comment]
After obtaining the 6D pose of an object, the 3D bounding box of the object can be estimated from the object's point cloud and normalized to the object's canonical space. We have defined operational methods in the canonical space for each category of objects and each task. Therefore, by combining the estimated pose of the object with these predefined operational methods, the manipulation of this category of objects can be realized.

**Comment by lfz-5** [comment]
> After obtaining the 6D pose of an object, the 3D bounding box of the object can be estimated from the object's point cloud and normalized to the object's canonical space. We have defined operational methods in the canonical space for each category of objects and each task. Therefore, by combining the estimated pose of the object with these predefined operational methods, the manipulation of this category of objects can be realized.

Hello, thanks for great work! Where can I find the code of this grasp part? I am very insterested in it. I would be very grateful if you could provide me with the sample code. Thank you again!

**Comment by Jiyao06** [comment]
> > After obtaining the 6D pose of an object, the 3D bounding box of the object can be estimated from the object's point cloud and normalized to the object's canonical space. We have defined operational methods in the canonical space for each category of objects and each task. Therefore, by combining the estimated pose of the object with these predefined operational methods, the manipulation of this category of objects can be realized.
> 
> Hello, thanks for great work! Where can I find the code of this grasp part? I am very insterested in it. I would be very grateful if you could provide me with the sample code. Thank you again!

We have only created a demo for the robotic grasping and have not yet organized it for release. However, the implementation is relatively simple. I would be delighted to assist if you encounter any issues during replication.
