### ISSUE TITLE
have no mug_meta.pkl 

### ISSUE THREAD

**Issue by wh631q** [Jiyao06/GenPose#32]
you mention that you “Preprocess NOCS files following [SPD](https://github.com/mentian/object-deformnet).”
But I have no mug_meta.pkl and cant generate it by shape_data.py  mentioned in issue of [SPD](https://github.com/mentian/object-deformnet)

**Comment by Jiyao06** [comment]
Do you mean `mug_handle.pkl`？If so, you can refer to #4

**Comment by wh631q** [comment]
Thanks 👍
