### ISSUE TITLE
mug_handle files 

### ISSUE THREAD

**Issue by taeyeopl** [Jiyao06/GenPose#4]
Thanks for sharing the codes. Can you also share the **mug_handle.pkl** files? 
https://github.com/Jiyao06/GenPose/blob/ce4d62def9ae9d9a9a891d1bbba0247cc2de627e/datasets/datasets_genpose.py#L193

**Comment by Jiyao06** [comment]
I apologize for the confusion. I have updated the repo and you can find the **mug_handle.pkl** file in the latest repo.

**Comment by taeyeopl** [comment]
Thanks :+1:
