### ISSUE TITLE
train score_net

### ISSUE THREAD

**Issue by huiyang0613** [Jiyao06/GenPose#6]
![image](https://github.com/Jiyao06/GenPose/assets/115716973/b14deaae-6905-4f6a-9eb4-88c2700ec911)
这里的训练周期是否是190而不是1900呢

**Comment by Jiyao06** [comment]
The training epochs for "ScoreNet" and "EnergyNet" are 1900 and 200, respectively. Furthermore, to enhance comprehension for individuals with similar questions, it would be appreciated if subsequent questions were posed in English. Thank you.

**Comment by huiyang0613** [comment]
> The training epochs for "ScoreNet" and "EnergyNet" are 1900 and 200, respectively. Furthermore, to enhance comprehension for individuals with similar questions, it would be appreciated if subsequent questions were posed in English. Thank you.

If the training epoch of ScoreNet is 1900, then how long does it take to train? It takes about 18 minutes for me to train one epoch on RTX3090.

**Comment by Jiyao06** [comment]
Training one epoch on a single RTX 3090 can be completed in under 10 minutes. If you want to improve your training speed, you can consider using multiple cards in parallel.

**Comment by huiyang0613** [comment]
> Training one epoch on a single RTX 3090 can be completed in under 10 minutes. If you want to improve your training speed, you can consider using multiple cards in parallel.

Thank you very much for your answer~

**Comment by fuzhao123232** [comment]
> > The training epochs for "ScoreNet" and "EnergyNet" are 1900 and 200, respectively. Furthermore, to enhance comprehension for individuals with similar questions, it would be appreciated if subsequent questions were posed in English. Thank you.
> 
> If the training epoch of ScoreNet is 1900, then how long does it take to train? It takes about 18 minutes for me to train one epoch on RTX3090.

你好兄弟，请问你有复现作者的结果吗，最后train score的loss降低到了多少啊？
