### ISSUE TITLE
Question about Batch Size and Class

### ISSUE THREAD

**Issue by taeyeopl** [Jiyao06/GenPose#7]
I have a question related to inference. I saw your provided script inference per class with a 256 batch size. 

Q. Do you think the per-frame inference (ex, five instances with different classes, 5 batch sizes) affects the performance? Would the smaller batch size and different classes in the batch influence the performance? 

Are the inference structures (per class inference) all only for efficient inference?

**Comment by Jiyao06** [comment]
Inference performance is unaffected by smaller batch sizes or class diversity in the batch because our method utilizes a single model to infer all classes without requiring prior knowledge of the object's category. Per-class inference is primarily used for efficiency and visualization.
