### ISSUE TITLE
Question about Pose Tracking 

### ISSUE THREAD

**Issue by taeyeopl** [Jiyao06/GenPose#8]
I'm interested in testing the pose tracking. May I ask when the object pose tracking will be released?
I am really looking forward to seeing the codes with the test data. 

If I want to do object pose tracking via the PF-ODE, does it work by defining '**init_x**' as the initial pose? Or Do we need more things to do?

https://github.com/Jiyao06/GenPose/blob/b83982e6227f2cee8fa90bc8ea189549373235f4/networks/gf_algorithms/samplers.py#L180

**Comment by Jiyao06** [comment]
Thanks for your interest! Apologies for the late reply. The code and manually processed data for tracking are now available on this repository.

For object pose tracking, in addition to defining 'init_x' as the initial pose, it's also important to adjust the initial 'T'. Ensure both parameters are correctly configured.

**Comment by taeyeopl** [comment]
Thanks for your help!
