### ISSUE TITLE
Question about the dataset generation.

### ISSUE THREAD

**Issue by yl-wang996** [Jiyao06/GenPose#9]
I am kind of confused about several items in `datasets_genpose.py`. I have some questions about the content in this file.

1. At Line 320, you used:  `fsnet_scale, mean_shape = self.get_fs_net_scale(self.id2cat_name[str(cat_id + 1)], model, nocs_scale)`, what means `fsnet_scale, mean_shape`? What's your motivation to do so? And if I want to build a customized dataset, what am I supposed to do with it?
2. As my understanding,  the `nocs_scale` in the `data_dict` means the scale of the normalized 3D model for the observed object, and `model_point` means sampled points cloud from the same 3D model.  Am I right?

Thanks in advance
Yunlong

**Comment by Jiyao06** [comment]
The questions you mentioned, including fsnet_scale and mean_shape, are primarily for data augmentation. We have followed the data augmentation strategy from [GPV-Pose](https://github.com/lolrudy/GPV_Pose) in this implementation. 

If you're interested in creating your dataset, I recommend referring to our work [DREDS](https://github.com/PKU-EPIC/DREDS). The released code includes detailed methods for generating category-level object pose estimation datasets.

**Comment by yl-wang996** [comment]
Thanks for your answer, since I don't have those 3D models, then I can use the preset value for `fsnet_scale` and `mean_shape`, anyway, I can try the training without data augmentation.
